run:
  timeout: 5m
  go: "1.24"
  tests: true

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - goconst
    - gocyclo
    - gofmt
    - misspell
    - revive
    - stylecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    enable:
      - fieldalignment
      - shadow
  gocyclo:
    min-complexity: 25
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
